name = "inhal-poc"
main = "src/index.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "inhal-poc"
database_id = "8f412848-d213-4bb3-aeb7-0aff221f9ee3"
